NANOSECS = 1
MICROSECS = 1000 * NANOSECS
MILLISECS = 1000 * MICROSECS
SECS = 1000 * MILLISECS

MINE_RATE = 4 * SECS

STARTING_BALANCE = 1000

MINING_REWARD = 50
MINING_REWARD_INPUT = {"address": "*--official-mining-reward--*"}